## Put comments here that give an overall description of what your
## functions do

## This function sets the variable m to NULL< where m is the placeholder for the inverse matrix.
## A matrix is passed in to the variable x via the function call.
## It also defines the four functions set, get, setInverse, getInverse, and returns in a list.

makeCacheMatrix <- function(x = matrix()) {
        m <- NULL#sets m to null
        #this next step defines the set function
        set<- function(y) {
                x <<- y
                m <<- NULL
        }
        #define get function
        get <- function() x
        #define setmean function - what does this do?
        setInverse <- function(inverse) m <<- inverse
        #define getmean
        getInverse <- function() m
        #returns list
        print(m)
        list(set = set, get = get,
             setInverse = setInverse,
             getInverse = getInverse)
 }


## This function is called using the list of functions generated by makeCacheMatrix
## It first looks to see if inverse has been calculated and if not does so, stores to cache,and 
## returns the inverse
## If inverse matrix is in the cache, it returns it without caclulating.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        m <- x$getInverse()
        if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        data <- x$get()
        m <- solve(data, ...)
        x$setInverse(m)
        m
}
